crud/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todos/', include('todos.urls')),
]

todos/urls.py
from django.urls import path
from . import views

app_name = 'todos'
urlpatterns = [
    path('', views.index, name='index'),
    path('detail/<int:todo_pk>/', views.detail, name='detail'),
    path('create/', views.create, name='create'),
    path('update/<int:todo_pk>/', views.update, name='update'),
    path('delete/<int:todo_pk>/', views.delete, name='delete'),
    path('category/', views.category, name='category'),
    path('sorting/', views.sorting, name='sorting'),
    path('completed/<int:todo_pk>', views.completed, name='completed'),
]

todos/models.py
from django.db import models

# Create your models here.
class Todo(models.Model):
    title = models.CharField(max_length=80)
    category = models.CharField(max_length=10, null=True)
    deadline = models.DateField(null=True)
    content = models.TextField()
    created_at = models.DateField(auto_now_add=True)
    completed = models.BooleanField(default=False)

todos/forms.py
from django import forms
from .models import Todo

class TodoForm(forms.ModelForm):
    title = forms.CharField(
        label='할 일',
        widget=forms.TextInput(
            attrs={
                'class': 'my-title',
                'placeholder': '할 일을 입력해주세요',
            },
        ),
    )

    deadline = forms.DateField(
        label='마감일',
        widget=forms.DateInput(
            attrs={'type': 'date'},
        ),
    )

    CHOICES = (('집안일', '집안일'), ('문화생활', '문화생활'), ('업무', '업무'), ('자기계발', '자기계발'))

    category = forms.ChoiceField(
        label='카테고리',
        choices=CHOICES,
        widget=forms.Select,
    )

    content = forms.CharField(
        label='내 용',
        widget=forms.Textarea(
            attrs={
                'cols': 44,
                'rows': 3,
                'class': 'my-content',
                'placeholder': '내용을 입력해주세요',
            },
        ),
    )
    
    class Meta:
        model = Todo
        exclude = ('completed',)


class CompleteForm(forms.ModelForm):
    completed = forms.BooleanField(
        widget=forms.CheckboxInput(
        attrs={
            'class': 'check-box',
            },
        ),
    )
    class Meta:
        model = Todo
        fields = ('completed',)

todos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Todo
from .forms import TodoForm, CompleteForm

# Create your views here.
def index(request):
    todos_yet = Todo.objects.filter(completed=False)
    todos_done = Todo.objects.filter(completed=True)
    todos_num = Todo.objects.all().count()
    todos_done_num = Todo.objects.filter(completed=True).count()
    complete_form = CompleteForm()
    context = {
        'todos_yet': todos_yet,
        'todos_done': todos_done,
        'todos_num': todos_num,
        'todos_done_num': todos_done_num,
        'complete_form': complete_form,
    }
    return render(request, 'todos/index.html', context)


def detail(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    context = {
        'todo': todo,
    }
    return render(request, 'todos/detail.html', context)


def create(request):
    todos_num = Todo.objects.all().count()
    todos_done_num = Todo.objects.filter(completed=True).count()
    if request.method == 'POST':
        form = TodoForm(request.POST)
        if form.is_valid():
            todo = form.save()
            return redirect('todos:index')
    else:
        form = TodoForm()
    context = {
        'form': form,
        'todos_num': todos_num,
        'todos_done_num': todos_done_num,
    }
    return render(request, 'todos/create.html', context)


def update(request, todo_pk):
    todos_num = Todo.objects.all().count()
    todos_done_num = Todo.objects.filter(completed=True).count()
    todo = Todo.objects.get(pk=todo_pk)
    if request.method == 'POST':
        form = TodoForm(request.POST, instance=todo)
        if form.is_valid():
            form.save()
            return redirect('todos:index')
    else:
        form = TodoForm(instance=todo)
    context = {
        'form': form,
        'todo': todo,
        'todos_num': todos_num,
        'todos_done_num': todos_done_num,
    }
    return render(request, 'todos/update.html', context)


def delete(request, todo_pk):
    todo = Todo.objects.get(pk=todo_pk)
    todo.delete()
    return redirect('todos:index')


def category(request):
    category_mode = request.GET.get('category_mode')
    if category_mode == '전체':
        todos_yet = Todo.objects.all()
    elif category_mode == '집안일':
        todos_yet = Todo.objects.filter(category='집안일')
    elif category_mode == '문화생활':
        todos_yet = Todo.objects.filter(category='문화생활')
    elif category_mode == '업무':
        todos_yet = Todo.objects.filter(category='업무')
    elif category_mode == '자기계발':
        todos_yet = Todo.objects.filter(category='자기계발')
    todos_num = Todo.objects.all().count()
    todos_done_num = Todo.objects.filter(completed=True).count()
    context = {
        'todos_yet': todos_yet,
        'todos_num': todos_num,
        'todos_done_num': todos_done_num,
    }
    return render(request, 'todos/index.html', context)


def sorting(request):
    print(request.GET.get('sorting_mode'))
    sorting_mode = request.GET.get('sorting_mode')
    if sorting_mode == '생성날짜순':
        todos_yet = Todo.objects.all().order_by('created_at')
    elif sorting_mode == '카테고리순':
        todos_yet = Todo.objects.all().order_by('category')
    elif sorting_mode == '마감날짜순':
        todos_yet = Todo.objects.all().order_by('deadline')
    context = {
        'todos_yet': todos_yet,
    }
    return render(request, 'todos/index.html', context)


def completed(request, todo_pk):
    todo = get_object_or_404(Todo, pk=todo_pk)
    todo.completed = not todo.completed
    todo.save()
    return redirect('todos:index')

todos/templates/todos/!base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>To Do List</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-aFq/bzH65dt+w6FI2ooMVUpc+21e0SRygnTpmBvdBgSdnuTN7QbdgL+OapgHtvPp" crossorigin="anonymous">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200" />
  {% block script %}{% endblock script %}
  <style>
    body {
      position: relative;
      background-color: #ebecef;
      width: 100%;
    }

    a {
      text-decoration: none;
      color: #333333
    }

    .padding {
      padding-right: 10%;
      padding-left: 10%;
    }
  
    .margin {
      margin-right: 10%;
      margin-left: 10%;
    }

    .navbar {
      background-color: white;
      height: 80px;
    }

    .task-cnt {
      height: 40px;
      padding-top: 8px;
      padding-right: 10px;
      padding-left: 10px;
      font-size: 15px;
      border-radius: 8px;
      background-color: #E0E0E0;
    }
    {% block style %}{% endblock style %}
  </style>
</head>
<body>
  <div class="container-fluid m-0 p-0" style="width: 100%;">
      {% comment %} 네비게이션 바 {% endcomment %}
      <div class="navbar d-flex justify-content-between padding">
        <a href="{% url 'todos:index' %}"><h2>To Do LIST 🗓️</h2></a>
        <div class='task-cnt'>
            <span>Tasks</span>
            <span>{{ todos_done_num }} / {{ todos_num }}</span>
        </div>
    </div>
    {% block body %}{% endblock body %}
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha2/dist/js/bootstrap.bundle.min.js" integrity="sha384-qKXV1j0HvMUeCBQ+QVp7JcfGl760yU08IQ+GpUo5hlbpg51QRiuqHAJz8+BrxE/N" crossorigin="anonymous"></script>
</body>
</html>

todos/templates/todos/create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="mt-4 mb-4 padding">
        <h3 class='mb-4'>생성하기</h3>
        <hr>
        <form action="{% url 'todos:create' %}" method='POST'>
            {% csrf_token %}
            {% for field in form %}
            <div class="mb-2">
                <div>
                    {{ field.label }}
                </div>
                <div>
                    {{ field }}
                </div>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-secondary mb-1">생 성</button>
        </form>
    </div>
</body>
</html>

todos/templates/todos/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    {% comment %} update_modal 실행시, update url 가져오기 {% endcomment %}
    <script>
        $(document).ready(function() {
            $("#update").on("show.bs.modal", function(e) {
            var $modal = $(this);
            var remoteUrl = e.relatedTarget.dataset.remote;
            if (remoteUrl) {
                $modal.find(".modal-content").load(remoteUrl);
            }
            });
        });
    </script>
</head>
<body>
    <div class="mt-4 mb-4 padding">
        <div class='d-flex align-items-center gap-3'>
            <h3 class='flex-grow-1'>{{ todo.title }}</h3>
            <a data-remote="{% url 'todos:update' todo.pk %}" class='text-center font-lightgray cursor' data-bs-toggle="modal" data-bs-target="#update">
                <span class="material-symbols-outlined">
                    edit
                </span>
            </a>
            <a href="{% url 'todos:delete' todo.pk %}" class='text-center font-lightgray' onclick="return confirm('정말 삭제하시겠습니까?');">
                <span class="material-symbols-outlined">
                    delete
                </span>
            </a>
        </div>
        
        <hr>

        <div class='container mb-3'>
            <div class='d-flex align-items-center'>
                <p class='col-2 font-12 font-lightgray'>카테고리</p>
                <p class='col-10'>{{ todo.category }}</p>
            </div>
            <div class='d-flex align-items-center'>
                <p class='col-2 font-12 font-lightgray'>생성날짜</p>
                <p class='col-10'>{{ todo.created_at }}</p>
            </div>
            <div class='d-flex align-items-center'>
                <p class='col-2 font-12 font-lightgray'>마감날짜</p>
                <p class='col-10'>{{ todo.deadline }}</p>
            </div>
            <div class='d-flex align-items-center'>
                <p class='col-2 font-12 font-lightgray'>내용</p>
                <p class='col-10'>{{ todo.content }}</p>
            </div>
        </div>
    </div>
    
    {% comment %} update_modal {% endcomment %}
    <div class="modal fade" id="update" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
            </div>
        </div>
    </div>
</body>
</html>

todos/templates/todos/index.html
{% extends 'todos/!base.html' %}

{% block script %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

{% comment %} detail_modal 실행시, detail url 가져오기 {% endcomment %}
<script>
    $(document).ready(function() {
        $("#detail").on("show.bs.modal", function(e) {
        var $modal = $(this);
        var remoteUrl = e.relatedTarget.dataset.remote;
        if (remoteUrl) {
            $modal.find(".modal-content").load(remoteUrl);
        }
        });
    });
</script>

{% comment %} create_modal 실행시, create url 가져오기 {% endcomment %}
<script>
    $(document).ready(function() {
        $("#create").on("show.bs.modal", function(e) {
        var $modal = $(this);
        var remoteUrl = e.relatedTarget.dataset.remote;
        if (remoteUrl) {
            $modal.find(".modal-content").load(remoteUrl);
        }
        });
    });
</script>

{% comment %} update_modal 실행시, update url 가져오기 {% endcomment %}
<script>
    $(document).ready(function() {
        $("#update").on("show.bs.modal", function(e) {
        var $modal = $(this);
        var remoteUrl = e.relatedTarget.dataset.remote;
        if (remoteUrl) {
            $modal.find(".modal-content").load(remoteUrl);
        }
        });
    });
</script>
{% endblock script %}


{% block style %}
.create-btn {
    height: 36px;
    margin-top: 4px;
    font-size: 15px;
    padding-bottom: 3px;
}

.card-form {
    height: 65px;
    border: none;
    background-color: white;
    border-radius: 10px;
    transition: all 0.2s linear;
}

.card-form:hover {
    border: 0.2px solid gray;
    box-shadow: 1px 1px 10px lightgray;
}

.arrange {
    transition: all 0.2s linear;
}

.arrange:hover {
    transform: scale(1.1);
    color: #333333;
}

.cursor {
    cursor: pointer;
}

.cate-home {
    height: 50px;
    width: 6px;
    background-color: #F1C0C0;
    margin-right: 10px;
    margin-left: 8px;
}

.cate-culture {
    height: 50px;
    width: 6px;
    background-color: #E4F1C0;
    margin-right: 10px;
    margin-left: 8px;
}

.cate-work {
    height: 50px;
    width: 6px;
    background-color: #C0CEF1;
    margin-right: 10px;
    margin-left: 8px;
}

.cate-study {
    height: 50px;
    width: 6px;
    background-color: #F1E6C0;
    margin-right: 10px;
    margin-left: 8px;
}

.check-box {
    border: 1.2px solid #999999;
    width: 100%;
    height: 100%;
}

.top-btn {
    position: fixed;
    bottom: 35px;
    right: 35px;
    width: 45px;
    height: 45px;
    background-color: #5C636A;
    color: white;
    border-radius: 20%;
    text-align: center;
    line-height: 55px;
    z-index: 1000;
}

.select-box {
    height: 37px;
    margin-top: 4px;
    background-color: #6c757d;
    color: white;
    font-size: 15px;
}

.top-btn:active {
    background-color: #444444;
}

.font-gray {
    color: #777777;
}

.font-lightgray {
    color: #999999;
}

.font-18 {
    font-size: 18px;
}

.font-14 {
    font-size: 14px;
}

.font-12 {
    font-size: 12px;
}

.text-center {
    text-align: center;
}

.nothing {
    margin-top: 12rem;
    font-size: 30px;
    text-align: center;
}
{% endblock style %}


{% block body %}
    {% comment %} 정렬 및 카테고리, 생성버튼 {% endcomment %}
    <div class="d-flex justify-content-between mt-4 mb-4 padding align-items-center">
        <h3>Tasks</h3>

        {% comment %} 필드별 정렬버튼 {% endcomment %}
        <span class="font-gray font-14 ms-4">정렬 | </span>
        <a href="{% url 'todos:sorting' %}" class='arrange font-gray font-14 ms-3' type='submit' name='sorting_mode' value='생성날짜순'>생성날짜순</a>
        <a href="{% url 'todos:sorting' %}" class='arrange font-gray font-14 ms-3' type='submit' name='sorting_mode' value='카테고리순'>카테고리순</a>
        <a href="{% url 'todos:sorting' %}" class='arrange font-gray font-14 ms-3' type='submit' name='sorting_mode' value='마감날짜순'>마감날짜순</a>

        <div class="flex-grow-1"></div>

        {% comment %} 카테고리별 조회 select {% endcomment %}
        <form action="{% url 'todos:category' %}" method='GET'>
            <select class="form-select select-box" name='category_mode' onChange="form.submit()">
                <option selected>카테고리별</option>
                <option value="전체">전체</option>
                <option value="집안일">집안일</option>
                <option value="문화생활">문화생활</option>
                <option value="업무">업무</option>
                <option value="자기계발">자기계발</option>
            </select>
        </form>

        {% comment %} 할 일 생성 버튼 {% endcomment %}
        <a data-remote="{% url 'todos:create' %}" class='btn btn-secondary create-btn ms-3' data-bs-toggle="modal" data-bs-target="#create">+ 할 일 생성</a>
    </div>

    {% if todos_yet %}
        {% comment %} 할 일 카드 라벨 {% endcomment %}
        <div class='d-flex justify-content-between padding font-14'>
            <span class="font-lightgray col-4 flex-grow-1 ms-4">할 일</span>
            <span class="font-lightgray col-2 text-center">카테고리</span>
            <span class="font-lightgray col-2 text-center">마감일</span>
            <span class="font-lightgray col-1 text-center">수 정</span>
            <span class="font-lightgray col-1 text-center">삭 제</span>
            <span class="font-lightgray col-1 text-center">완 료</span>
        </div>

        {% comment %} 할 일 카드 {% endcomment %}
        <div class='mb-5'>
            {% for todo in todos_yet %}
                <div class="card-form d-flex align-items-center mt-3 margin">

                    {% comment %} 색상태그 {% endcomment %}
                    <div class='{% if todo.category == '집안일' %} cate-home
                                {% elif todo.category == '문화생활' %} cate-culture
                                {% elif todo.category == '업무' %} cate-work
                                {% elif todo.category == '자기계발' %} cate-study{% endif %}'></div>

                    {% comment %} 할 일 title, created_at {% endcomment %}
                    <div class='d-flex row col-5'>
                        <a data-remote="{% url 'todos:detail' todo.pk %}" class='font-18 cursor' data-bs-toggle="modal" data-bs-target="#detail">
                            {{ todo.title }}
                        </a>
                        <span class='font-12 font-lightgray'>{{ todo.created_at|date:'Y-m-d' }}</span>
                    </div>

                    {% comment %} 할 일 category, deadline {% endcomment %}
                    <span class='col-2 text-center font-lightgray font-14'>{{ todo.category }}</span>
                    <span class='col-2 text-center font-lightgray font-14'>{{ todo.deadline|date:'Y-m-d' }}</span>

                    {% comment %} edit {% endcomment %}
                    <a data-remote="{% url 'todos:update' todo.pk %}" class='col-1 text-center font-lightgray mt-1 cursor' data-bs-toggle="modal" data-bs-target="#update">
                        <span class="material-symbols-outlined">
                            edit
                        </span>
                    </a>

                    {% comment %} delete {% endcomment %}
                    <a href="{% url 'todos:delete' todo.pk %}" class='col-1 text-center font-lightgray mt-1' onclick="return confirm('정말 삭제하시겠습니까?');">
                        <span class="material-symbols-outlined">
                            delete
                        </span>
                    </a>

                    {% comment %} check {% endcomment %}
                    <div class="col-1 mx-auto">
                        <form action="{% url 'todos:completed' todo.pk %}" method='POST' id='complete-form'>
                            {% csrf_token %}
                            {% for field in complete_form %}
                                {{ field }}
                            {% endfor %}
                        </form>
                    </div>
                </div>
            {% endfor %}

            {% comment %} 위로가기 버튼 {% endcomment %}
            <a href="#top" class='top-btn'>
                <span class="material-symbols-outlined">
                    arrow_upward
                </span>
            </a>
        </div>
        {% if todos_done %}
            <hr>
            <div class="d-flex justify-content-between mt-4 mb-4 padding align-items-center">
                <h3>Tasks</h3>

                {% comment %} 완료한 할 일 카드 {% endcomment %}
                <div class='mb-5'>
                    {% for todo in todos_done %}
                        <div class="card-form d-flex align-items-center mt-3 margin">
                            <div class='{% if todo.category == '집안일' %} cate-home {% elif todo.category == '문화생활' %} cate-culture {% elif todo.category == '업무' %} cate-work {% elif todo.category == '자기계발' %} cate-study {% endif %}'></div>
                            <div class='d-flex row col-5'>
                            <a href="{% url 'todos:detail' todo.pk %}" class='font-18'>{{ todo.title }}</a>
                            <span class='font-12 font-lightgray'>{{ todo.created_at|date:'Y-m-d' }}</span>
                        </div>
                        <span class='col-2 text-center font-lightgray font-14'>{{ todo.category }}</span>
                        <span class='col-2 text-center font-lightgray font-14'>{{ todo.deadline|date:'Y-m-d' }}</span>

                        {% comment %} edit, delete, check {% endcomment %}
                        <a href="{% url 'todos:update' todo.pk %}" class='col-1 text-center font-lightgray mt-1'>
                            <span class="material-symbols-outlined">
                                edit
                            </span>
                        </a>
                        <a href="{% url 'todos:delete' todo.pk %}" class='col-1 text-center font-lightgray mt-1'>
                            <span class="material-symbols-outlined">
                                delete
                            </span>
                        </a>
                        <input class="form-check-input check-box mx-auto col-1 mt-0" type="checkbox" aria-label="Checkbox for following text input">
                    </div>
                {% endfor %}
            </div>
        {% endif %}
    {% else %}
        <div class='nothing'>
            <span class='font-lightgray'>할 일을 생성해주세요.<br></span>
            <span class='font-lightgray font-18'>There's nothing to do. Please create something to do.</span>
        </div>
    {% endif %}


    {% comment %} detail_modal {% endcomment %}
    <div class="modal fade" id="detail" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
            </div>
        </div>
    </div>

    {% comment %} create_modal {% endcomment %}
    <div class="modal fade" id="create" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
            </div>
        </div>
    </div>

    {% comment %} update_modal {% endcomment %}
    <div class="modal fade" id="update" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
            </div>
        </div>
    </div>

    <script>
        document.getElementById("complete-form").addEventListener("click", function() {
            if (document.getElementById("complete-form").checked) {
                document.getElementById("complete-form").submit();
            }
        });
    </script>
{% endblock body %}

todos/templates/todos/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="mt-4 mb-4 padding">
        <h3 class='mb-4'>수정하기</h3>
        <hr>
        <form action="{% url 'todos:update' todo.pk %}" method='POST'>
            {% csrf_token %}
            {% for field in form %}
            <div class="mb-2">
                <div>
                    {{ field.label }}
                </div>
                <div>
                    {{ field }}
                </div>
            </div>
            {% endfor %}
            <button type="submit" class="btn btn-secondary mb-1">수 정</button>
        </form>
    </div>
</body>
</html>